version: "3.8"

services:
    app:
        build: .
        command: sh -c "python main.py"
        # Replace username to your Docker Hub user
        image: username/repo:latest
        ports:
            - "80:8000"
        volumes:
            - ./src:/src