version: "3.8"

services:
    app:
        build: .
        command: sh -c "python main.py"
        # Replace uxername to your Docker Hub user
        image: ronnic/cicd_docker:latest
        ports:
            - "80:8000"
        volumes:
            - ./src:/src